version: '3'

services:
  pg13:
    build:
      args:
        - POSTGRES_VERSION=13
      context: ./postgis
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    ports:
      - "5439:5432"
    command: postgres -N 500

  pg14:
    build:
      args:
        - POSTGRES_VERSION=14
      context: ./postgis
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    ports:
      - "5439:5432"
    command: postgres -N 500

  pg15:
    build:
      args:
        - POSTGRES_VERSION=15
      context: ./postgis
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    ports:
      - "5439:5432"
    command: postgres -N 500

  gunicorn-py38:
    build:
      args:
        - PYTHON_VERSION=3.8
      context: ./uvicorn-gunicorn
      dockerfile: Dockerfile

  gunicorn-py39:
    build:
      args:
        - PYTHON_VERSION=3.9
      context: ./uvicorn-gunicorn
      dockerfile: Dockerfile

  gunicorn-py310:
    build:
      args:
        - PYTHON_VERSION=3.10
      context: ./uvicorn-gunicorn
      dockerfile: Dockerfile

  gunicorn-py311:
    build:
      args:
        - PYTHON_VERSION=3.11
      context: ./uvicorn-gunicorn
      dockerfile: Dockerfile

  hypercorn-py38:
    build:
      args:
        - PYTHON_VERSION=3.8
      context: ./hypercorn
      dockerfile: Dockerfile

  hypercorn-py39:
    build:
      args:
        - PYTHON_VERSION=3.9
      context: ./hypercorn
      dockerfile: Dockerfile

  hypercorn-py310:
    build:
      args:
        - PYTHON_VERSION=3.10
      context: ./hypercorn
      dockerfile: Dockerfile

  hypercorn-py311:
    build:
      args:
        - PYTHON_VERSION=3.11
      context: ./hypercorn
      dockerfile: Dockerfile
