services:
  pg14:
    build:
      args:
        - POSTGRES_VERSION=14
      context: ./postgis
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    ports:
      - "5439:5432"
    command: postgres -N 500

  pg15:
    build:
      args:
        - POSTGRES_VERSION=15
      context: ./postgis
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    ports:
      - "5439:5432"
    command: postgres -N 500

  pg16:
    build:
      args:
        - POSTGRES_VERSION=16
      context: ./postgis
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    ports:
      - "5439:5432"
    command: postgres -N 500


  pg17:
    build:
      args:
        - POSTGRES_VERSION=17
      context: ./postgis
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    ports:
      - "5439:5432"
    command: postgres -N 500

  pg18:
    build:
      args:
        - POSTGRES_VERSION=18
      context: ./postgis
      dockerfile: Dockerfile.3.6
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
    ports:
      - "5439:5432"
    command: postgres -N 500
