name: CI

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

jobs:
  postgis:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        postgres: [13, 14]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./postgis/${{ matrix.postgres }}-3.1
          file: ./postgis/${{ matrix.postgres }}-3.1/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.actor }}/postgis:${{ matrix.postgres }}-3.1

      - name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: ./postgis/${{ matrix.postgres }}-3.1
          file: ./postgis/${{ matrix.postgres }}-3.1/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/postgis:${{ matrix.postgres }}-3.1

  uvicorn:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images
        uses: docker/build-push-action@v2
        with:
          context: ./uvicorn-gunicorn
          file: ./uvicorn-gunicorn/python${{ matrix.python }}.dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.actor }}/uvicorn-gunicorn:${{ matrix.python }}

      - name: push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: ./uvicorn-gunicorn
          file: ./uvicorn-gunicorn/python${{ matrix.python }}.dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/uvicorn-gunicorn:${{ matrix.python }}
